# Generated by Django 5.2.2 on 2025-06-08 09:01

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessclass',
            old_name='date_time',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='fitnessclass',
            name='total_slots',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='available_slots',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='name',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('Zumba', 'Zumba'), ('HIIT', 'HIIT')], max_length=100),
        ),
    ]
